server:
  port: 80
  session-timeout: 30
  tomcat.max-threads: 0
  tomcat.uri-encoding: UTF-8

# mysql 的数据库配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wechat?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  # spring mvc 视图解析器
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp